description = 'Source Resolver'

dependencies {
}

publishing {
    publications {
        maven(MavenPublication) {
            pom {
                description = 'Source Resolver'
                url = 'https://github.com/zamasoftnet/zstream/tree/main/zstream-resolver'
                
                scm {
                    connection = 'scm:git:https://github.com/zamasoftnet/zstream/tree/main/zstream-resolver'
                    developerConnection = 'scm:git:https://github.com/zamasoftnet/zstream/tree/main/zstream-resolver'
                    url = 'https://github.com/zamasoftnet/zstream/tree/main/zstream-resolver'
                }
            }
        }
    }
}
